//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  /** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  events: Events;
  eventsConnection: EventsConnection;
  writings: Writings;
  writingsConnection: WritingsConnection;
  talks: Talks;
  talksConnection: TalksConnection;
  testimonials: Testimonials;
  testimonialsConnection: TestimonialsConnection;
  site: Site;
  siteConnection: SiteConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryEventsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryEventsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EventsFilter>;
};


export type QueryWritingsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryWritingsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<WritingsFilter>;
};


export type QueryTalksArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTalksConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TalksFilter>;
};


export type QueryTestimonialsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTestimonialsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TestimonialsFilter>;
};


export type QuerySiteArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteFilter>;
};

export type DocumentFilter = {
  events?: InputMaybe<EventsFilter>;
  writings?: InputMaybe<WritingsFilter>;
  talks?: InputMaybe<TalksFilter>;
  testimonials?: InputMaybe<TestimonialsFilter>;
  site?: InputMaybe<SiteFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Events | Writings | Talks | Testimonials | Site | Folder;

export type Events = Node & Document & {
  __typename?: 'Events';
  title: Scalars['String']['output'];
  date?: Maybe<Scalars['String']['output']>;
  location?: Maybe<Scalars['String']['output']>;
  role?: Maybe<Scalars['String']['output']>;
  url?: Maybe<Scalars['String']['output']>;
  recap?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  featured?: Maybe<Scalars['Boolean']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type EventsFilter = {
  title?: InputMaybe<StringFilter>;
  date?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
  recap?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  featured?: InputMaybe<BooleanFilter>;
};

export type EventsConnectionEdges = {
  __typename?: 'EventsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Events>;
};

export type EventsConnection = Connection & {
  __typename?: 'EventsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<EventsConnectionEdges>>>;
};

export type Writings = Node & Document & {
  __typename?: 'Writings';
  title: Scalars['String']['output'];
  outlet?: Maybe<Scalars['String']['output']>;
  year?: Maybe<Scalars['Float']['output']>;
  url?: Maybe<Scalars['String']['output']>;
  summary?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  format?: Maybe<Scalars['String']['output']>;
  featured?: Maybe<Scalars['Boolean']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type WritingsFilter = {
  title?: InputMaybe<StringFilter>;
  outlet?: InputMaybe<StringFilter>;
  year?: InputMaybe<NumberFilter>;
  url?: InputMaybe<StringFilter>;
  summary?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  format?: InputMaybe<StringFilter>;
  featured?: InputMaybe<BooleanFilter>;
};

export type WritingsConnectionEdges = {
  __typename?: 'WritingsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Writings>;
};

export type WritingsConnection = Connection & {
  __typename?: 'WritingsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<WritingsConnectionEdges>>>;
};

export type Talks = Node & Document & {
  __typename?: 'Talks';
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  formats?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  order?: Maybe<Scalars['Float']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type TalksFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  formats?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
};

export type TalksConnectionEdges = {
  __typename?: 'TalksConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Talks>;
};

export type TalksConnection = Connection & {
  __typename?: 'TalksConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TalksConnectionEdges>>>;
};

export type Testimonials = Node & Document & {
  __typename?: 'Testimonials';
  quote?: Maybe<Scalars['String']['output']>;
  name: Scalars['String']['output'];
  role?: Maybe<Scalars['String']['output']>;
  organisation?: Maybe<Scalars['String']['output']>;
  type?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type TestimonialsFilter = {
  quote?: InputMaybe<StringFilter>;
  name?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  organisation?: InputMaybe<StringFilter>;
  type?: InputMaybe<StringFilter>;
};

export type TestimonialsConnectionEdges = {
  __typename?: 'TestimonialsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Testimonials>;
};

export type TestimonialsConnection = Connection & {
  __typename?: 'TestimonialsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TestimonialsConnectionEdges>>>;
};

export type Site = Node & Document & {
  __typename?: 'Site';
  hero_line1?: Maybe<Scalars['String']['output']>;
  hero_line2?: Maybe<Scalars['String']['output']>;
  hero_sub?: Maybe<Scalars['String']['output']>;
  tagline?: Maybe<Scalars['String']['output']>;
  profile_photo?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type SiteFilter = {
  hero_line1?: InputMaybe<StringFilter>;
  hero_line2?: InputMaybe<StringFilter>;
  hero_sub?: InputMaybe<StringFilter>;
  tagline?: InputMaybe<StringFilter>;
  profile_photo?: InputMaybe<ImageFilter>;
};

export type SiteConnectionEdges = {
  __typename?: 'SiteConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Site>;
};

export type SiteConnection = Connection & {
  __typename?: 'SiteConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SiteConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateEvents: Events;
  createEvents: Events;
  updateWritings: Writings;
  createWritings: Writings;
  updateTalks: Talks;
  createTalks: Talks;
  updateTestimonials: Testimonials;
  createTestimonials: Testimonials;
  updateSite: Site;
  createSite: Site;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateEventsArgs = {
  relativePath: Scalars['String']['input'];
  params: EventsMutation;
};


export type MutationCreateEventsArgs = {
  relativePath: Scalars['String']['input'];
  params: EventsMutation;
};


export type MutationUpdateWritingsArgs = {
  relativePath: Scalars['String']['input'];
  params: WritingsMutation;
};


export type MutationCreateWritingsArgs = {
  relativePath: Scalars['String']['input'];
  params: WritingsMutation;
};


export type MutationUpdateTalksArgs = {
  relativePath: Scalars['String']['input'];
  params: TalksMutation;
};


export type MutationCreateTalksArgs = {
  relativePath: Scalars['String']['input'];
  params: TalksMutation;
};


export type MutationUpdateTestimonialsArgs = {
  relativePath: Scalars['String']['input'];
  params: TestimonialsMutation;
};


export type MutationCreateTestimonialsArgs = {
  relativePath: Scalars['String']['input'];
  params: TestimonialsMutation;
};


export type MutationUpdateSiteArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteMutation;
};


export type MutationCreateSiteArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteMutation;
};

export type DocumentUpdateMutation = {
  events?: InputMaybe<EventsMutation>;
  writings?: InputMaybe<WritingsMutation>;
  talks?: InputMaybe<TalksMutation>;
  testimonials?: InputMaybe<TestimonialsMutation>;
  site?: InputMaybe<SiteMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  events?: InputMaybe<EventsMutation>;
  writings?: InputMaybe<WritingsMutation>;
  talks?: InputMaybe<TalksMutation>;
  testimonials?: InputMaybe<TestimonialsMutation>;
  site?: InputMaybe<SiteMutation>;
};

export type EventsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
  recap?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  featured?: InputMaybe<Scalars['Boolean']['input']>;
};

export type WritingsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  outlet?: InputMaybe<Scalars['String']['input']>;
  year?: InputMaybe<Scalars['Float']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
  summary?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  format?: InputMaybe<Scalars['String']['input']>;
  featured?: InputMaybe<Scalars['Boolean']['input']>;
};

export type TalksMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  formats?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  order?: InputMaybe<Scalars['Float']['input']>;
};

export type TestimonialsMutation = {
  quote?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  organisation?: InputMaybe<Scalars['String']['input']>;
  type?: InputMaybe<Scalars['String']['input']>;
};

export type SiteMutation = {
  hero_line1?: InputMaybe<Scalars['String']['input']>;
  hero_line2?: InputMaybe<Scalars['String']['input']>;
  hero_sub?: InputMaybe<Scalars['String']['input']>;
  tagline?: InputMaybe<Scalars['String']['input']>;
  profile_photo?: InputMaybe<Scalars['String']['input']>;
};

export type StringFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type ImageFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type BooleanFilter = {
  eq?: boolean | null | undefined;
  exists?: boolean | null | undefined;
};

export type EventsFilter = {
  title?: StringFilter | null | undefined;
  date?: StringFilter | null | undefined;
  location?: StringFilter | null | undefined;
  role?: StringFilter | null | undefined;
  url?: StringFilter | null | undefined;
  recap?: StringFilter | null | undefined;
  image?: ImageFilter | null | undefined;
  featured?: BooleanFilter | null | undefined;
};

export type NumberFilter = {
  lt?: number | null | undefined;
  lte?: number | null | undefined;
  gte?: number | null | undefined;
  gt?: number | null | undefined;
  eq?: number | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<number | null | undefined> | null | undefined;
};

export type WritingsFilter = {
  title?: StringFilter | null | undefined;
  outlet?: StringFilter | null | undefined;
  year?: NumberFilter | null | undefined;
  url?: StringFilter | null | undefined;
  summary?: StringFilter | null | undefined;
  image?: ImageFilter | null | undefined;
  format?: StringFilter | null | undefined;
  featured?: BooleanFilter | null | undefined;
};

export type TalksFilter = {
  title?: StringFilter | null | undefined;
  description?: StringFilter | null | undefined;
  image?: ImageFilter | null | undefined;
  formats?: StringFilter | null | undefined;
  order?: NumberFilter | null | undefined;
};

export type TestimonialsFilter = {
  quote?: StringFilter | null | undefined;
  name?: StringFilter | null | undefined;
  role?: StringFilter | null | undefined;
  organisation?: StringFilter | null | undefined;
  type?: StringFilter | null | undefined;
};

export type SiteFilter = {
  hero_line1?: StringFilter | null | undefined;
  hero_line2?: StringFilter | null | undefined;
  hero_sub?: StringFilter | null | undefined;
  tagline?: StringFilter | null | undefined;
  profile_photo?: ImageFilter | null | undefined;
};

export type EventsPartsFragment = { __typename: 'Events', title: string, date: string | null, location: string | null, role: string | null, url: string | null, recap: string | null, image: string | null, featured: boolean | null };

export type WritingsPartsFragment = { __typename: 'Writings', title: string, outlet: string | null, year: number | null, url: string | null, summary: string | null, image: string | null, format: string | null, featured: boolean | null };

export type TalksPartsFragment = { __typename: 'Talks', title: string, description: string | null, image: string | null, formats: Array<string | null> | null, order: number | null };

export type TestimonialsPartsFragment = { __typename: 'Testimonials', quote: string | null, name: string, role: string | null, organisation: string | null, type: string | null };

export type SitePartsFragment = { __typename: 'Site', hero_line1: string | null, hero_line2: string | null, hero_sub: string | null, tagline: string | null, profile_photo: string | null };

export type EventsQueryVariables = Exact<{
  relativePath: string;
}>;


export type EventsQuery = { events: { __typename: 'Events', id: string, title: string, date: string | null, location: string | null, role: string | null, url: string | null, recap: string | null, image: string | null, featured: boolean | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type EventsConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: EventsFilter | null | undefined;
}>;


export type EventsConnectionQuery = { eventsConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Events', id: string, title: string, date: string | null, location: string | null, role: string | null, url: string | null, recap: string | null, image: string | null, featured: boolean | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type WritingsQueryVariables = Exact<{
  relativePath: string;
}>;


export type WritingsQuery = { writings: { __typename: 'Writings', id: string, title: string, outlet: string | null, year: number | null, url: string | null, summary: string | null, image: string | null, format: string | null, featured: boolean | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type WritingsConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: WritingsFilter | null | undefined;
}>;


export type WritingsConnectionQuery = { writingsConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Writings', id: string, title: string, outlet: string | null, year: number | null, url: string | null, summary: string | null, image: string | null, format: string | null, featured: boolean | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type TalksQueryVariables = Exact<{
  relativePath: string;
}>;


export type TalksQuery = { talks: { __typename: 'Talks', id: string, title: string, description: string | null, image: string | null, formats: Array<string | null> | null, order: number | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type TalksConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: TalksFilter | null | undefined;
}>;


export type TalksConnectionQuery = { talksConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Talks', id: string, title: string, description: string | null, image: string | null, formats: Array<string | null> | null, order: number | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type TestimonialsQueryVariables = Exact<{
  relativePath: string;
}>;


export type TestimonialsQuery = { testimonials: { __typename: 'Testimonials', id: string, quote: string | null, name: string, role: string | null, organisation: string | null, type: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type TestimonialsConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: TestimonialsFilter | null | undefined;
}>;


export type TestimonialsConnectionQuery = { testimonialsConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Testimonials', id: string, quote: string | null, name: string, role: string | null, organisation: string | null, type: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type SiteQueryVariables = Exact<{
  relativePath: string;
}>;


export type SiteQuery = { site: { __typename: 'Site', id: string, hero_line1: string | null, hero_line2: string | null, hero_sub: string | null, tagline: string | null, profile_photo: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type SiteConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: SiteFilter | null | undefined;
}>;


export type SiteConnectionQuery = { siteConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Site', id: string, hero_line1: string | null, hero_line2: string | null, hero_sub: string | null, tagline: string | null, profile_photo: string | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const EventsPartsFragmentDoc = gql`
    fragment EventsParts on Events {
  __typename
  title
  date
  location
  role
  url
  recap
  image
  featured
}
    `;
export const WritingsPartsFragmentDoc = gql`
    fragment WritingsParts on Writings {
  __typename
  title
  outlet
  year
  url
  summary
  image
  format
  featured
}
    `;
export const TalksPartsFragmentDoc = gql`
    fragment TalksParts on Talks {
  __typename
  title
  description
  image
  formats
  order
}
    `;
export const TestimonialsPartsFragmentDoc = gql`
    fragment TestimonialsParts on Testimonials {
  __typename
  quote
  name
  role
  organisation
  type
}
    `;
export const SitePartsFragmentDoc = gql`
    fragment SiteParts on Site {
  __typename
  hero_line1
  hero_line2
  hero_sub
  tagline
  profile_photo
}
    `;
export const EventsDocument = gql`
    query events($relativePath: String!) {
  events(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...EventsParts
  }
}
    ${EventsPartsFragmentDoc}`;
export const EventsConnectionDocument = gql`
    query eventsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: EventsFilter) {
  eventsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...EventsParts
      }
    }
  }
}
    ${EventsPartsFragmentDoc}`;
export const WritingsDocument = gql`
    query writings($relativePath: String!) {
  writings(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...WritingsParts
  }
}
    ${WritingsPartsFragmentDoc}`;
export const WritingsConnectionDocument = gql`
    query writingsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: WritingsFilter) {
  writingsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...WritingsParts
      }
    }
  }
}
    ${WritingsPartsFragmentDoc}`;
export const TalksDocument = gql`
    query talks($relativePath: String!) {
  talks(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TalksParts
  }
}
    ${TalksPartsFragmentDoc}`;
export const TalksConnectionDocument = gql`
    query talksConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TalksFilter) {
  talksConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TalksParts
      }
    }
  }
}
    ${TalksPartsFragmentDoc}`;
export const TestimonialsDocument = gql`
    query testimonials($relativePath: String!) {
  testimonials(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TestimonialsParts
  }
}
    ${TestimonialsPartsFragmentDoc}`;
export const TestimonialsConnectionDocument = gql`
    query testimonialsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TestimonialsFilter) {
  testimonialsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TestimonialsParts
      }
    }
  }
}
    ${TestimonialsPartsFragmentDoc}`;
export const SiteDocument = gql`
    query site($relativePath: String!) {
  site(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SiteParts
  }
}
    ${SitePartsFragmentDoc}`;
export const SiteConnectionDocument = gql`
    query siteConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SiteFilter) {
  siteConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SiteParts
      }
    }
  }
}
    ${SitePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      events(variables: EventsQueryVariables, options?: C): Promise<{data: EventsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventsQueryVariables, query: string}> {
        return requester<{data: EventsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventsQueryVariables, query: string}, EventsQueryVariables>(EventsDocument, variables, options);
      },
    eventsConnection(variables?: EventsConnectionQueryVariables, options?: C): Promise<{data: EventsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventsConnectionQueryVariables, query: string}> {
        return requester<{data: EventsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventsConnectionQueryVariables, query: string}, EventsConnectionQueryVariables>(EventsConnectionDocument, variables, options);
      },
    writings(variables: WritingsQueryVariables, options?: C): Promise<{data: WritingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: WritingsQueryVariables, query: string}> {
        return requester<{data: WritingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: WritingsQueryVariables, query: string}, WritingsQueryVariables>(WritingsDocument, variables, options);
      },
    writingsConnection(variables?: WritingsConnectionQueryVariables, options?: C): Promise<{data: WritingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: WritingsConnectionQueryVariables, query: string}> {
        return requester<{data: WritingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: WritingsConnectionQueryVariables, query: string}, WritingsConnectionQueryVariables>(WritingsConnectionDocument, variables, options);
      },
    talks(variables: TalksQueryVariables, options?: C): Promise<{data: TalksQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TalksQueryVariables, query: string}> {
        return requester<{data: TalksQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TalksQueryVariables, query: string}, TalksQueryVariables>(TalksDocument, variables, options);
      },
    talksConnection(variables?: TalksConnectionQueryVariables, options?: C): Promise<{data: TalksConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TalksConnectionQueryVariables, query: string}> {
        return requester<{data: TalksConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TalksConnectionQueryVariables, query: string}, TalksConnectionQueryVariables>(TalksConnectionDocument, variables, options);
      },
    testimonials(variables: TestimonialsQueryVariables, options?: C): Promise<{data: TestimonialsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialsQueryVariables, query: string}> {
        return requester<{data: TestimonialsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialsQueryVariables, query: string}, TestimonialsQueryVariables>(TestimonialsDocument, variables, options);
      },
    testimonialsConnection(variables?: TestimonialsConnectionQueryVariables, options?: C): Promise<{data: TestimonialsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialsConnectionQueryVariables, query: string}> {
        return requester<{data: TestimonialsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialsConnectionQueryVariables, query: string}, TestimonialsConnectionQueryVariables>(TestimonialsConnectionDocument, variables, options);
      },
    site(variables: SiteQueryVariables, options?: C): Promise<{data: SiteQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteQueryVariables, query: string}> {
        return requester<{data: SiteQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteQueryVariables, query: string}, SiteQueryVariables>(SiteDocument, variables, options);
      },
    siteConnection(variables?: SiteConnectionQueryVariables, options?: C): Promise<{data: SiteConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteConnectionQueryVariables, query: string}> {
        return requester<{data: SiteConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteConnectionQueryVariables, query: string}, SiteConnectionQueryVariables>(SiteConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/2.4/content/e76c03ef-4caf-445c-a0a4-b4aab6854e5a/github/master",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

export type { Exact };

  